### ISSUE TITLE
Error on brew tap toonetown/android

### ISSUE THREAD

**Issue by caoilte** [toonetown/homebrew-android#3]
Hi,
brew tap toonetown/android is failing for us with the following error,

```
brew tap toonetown/android
==> Tapping toonetown/android
Cloning into '/usr/local/Homebrew/Library/Taps/toonetown/homebrew-android'...
remote: Counting objects: 223, done.
remote: Compressing objects: 100% (189/189), done.
remote: Total 223 (delta 182), reused 36 (delta 33), pack-reused 0
Receiving objects: 100% (223/223), 46.66 KiB | 0 bytes/s, done.
Resolving deltas: 100% (182/182), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/toonetown/homebrew-android/Formula/google-apis-25-sysimg-armv7.rb
google-apis-25-sysimg-armv7: /usr/local/Homebrew/Library/Taps/toonetown/homebrew-android/Formula/google-apis-25-sysimg-armv7.rb:8: syntax error, unexpected tIDENTIFIER, expecting keyword_end
...4c3a87cc965abe380a56980b"  desc "Google APIs ARM EABI v7a Sy...
...                               ^
Error: Cannot tap toonetown/android: invalid syntax in tap!
```

We think it's caused by a fat finger double C&P here,

https://github.com/toonetown/homebrew-android/commit/8ee1405b176621bc75070109ee9f58a7e1d5108e#diff-3f2997e51c83c3948dbd14c8f94c8ac6R8

I just forked and rolled back to the commit before and am able to get past this point in our build so it seems most likely to be the problem.

**Comment by toonetown** [comment]
Likely caused by a change to googles xml feed...all these formulas are auto generated from it. I will have to look into it next week some time

**Comment by caoilte** [comment]
Damn, that's a shame as the fix should be as simple as removing 4 lines of config. Thanks anyway.

**Comment by toonetown** [comment]
Yeah - If you want to do a pull request with the 4-line change, I'll merge it in...but the "real" fix is going to have to be in the scripts and XSL files that I run to keep the project up-to-date.  I'm out of town for the remainder of this week, so if you submit a PR that removes the duplicate lines, I can merge it from here.  But then I'll just have to remember to fix it for real before I run the update scripts again!  😄

**Comment by toonetown** [comment]
It looks like google fixed their XML feed - the formula is now working (and I've updated it)
